INSERT INTO reviews (name, country, flag, tour, rating, text, date, approved) VALUES
('Sarah Mitchell', 'United States', '🇺🇸', 'Golden Triangle Tour', 5, 'Our driver Rajesh was incredible! He knew all the best spots for photos, recommended amazing restaurants, and made our first trip to India absolutely magical. Can''t recommend Vibe Yatra enough!', '2025-11-15', 1),
('Michael & Anna', 'Germany', '🇩🇪', 'Rajasthan Royal Heritage Tour', 5, '10 days of pure magic! From Jaipur''s palaces to Jaisalmer''s desert, every moment was perfectly planned. The flexibility to change plans on the go was a game-changer.', '2025-10-20', 1),
('James Thompson', 'Australia', '🇦🇺', 'Leh Ladakh Adventure Tour', 5, 'The Ladakh trip was life-changing! Our driver navigated those mountain roads like a pro. Pangong Lake at sunrise is something I''ll never forget. Worth every penny!', '2025-09-05', 1),
('Emma Wilson', 'United Kingdom', '🇬🇧', 'Himachal Valley Tour', 5, 'Traveling solo as a woman, safety was my priority. Vibe Yatra exceeded all expectations. The driver was professional, the homestays were charming, and I felt completely safe throughout.', '2025-08-12', 1),
('Pierre Dubois', 'France', '🇫🇷', 'Classic Golden Triangle Tour', 5, 'From the Taj Mahal at sunrise to the bustling streets of Old Delhi, every moment was curated to perfection. Our driver was not just a chauffeur but a cultural guide. Magnifique!', '2025-12-01', 1),
('Yuki Tanaka', 'Japan', '🇯🇵', 'Rajasthan Palaces and Lakes Tour', 5, 'Udaipur stole my heart! The boat ride on Lake Pichola during sunset was surreal. The entire journey through Rajasthan felt like stepping into a fairy tale. Highly recommended!', '2025-07-28', 1),
('Carlos & Maria Rodriguez', 'Spain', '🇪🇸', 'Golden Triangle and Varanasi Spiritual Tour', 4, 'The spiritual experience in Varanasi combined with the grandeur of the Golden Triangle was unforgettable. The Ganga Aarti ceremony left us speechless. A truly transformative journey.', '2025-06-10', 1),
('Lisa van den Berg', 'Netherlands', '🇳🇱', 'Classic Himachal Hill Station Tour', 5, 'Shimla, Manali, and Dharamshala — each place had its own magic. The mountain roads were breathtaking, and our driver made us feel safe on every turn. Perfect escape from the heat!', '2025-05-18', 1),
('Hemant Rajput', 'India', '🇮🇳', 'Rajasthan Royal Heritage Tour', 5, 'It was one of the best experience I had and I fully recomend everyone to visit', '2026-02-21', 1);
